# Generated by Django 5.2.1 on 2025-06-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autobuses/')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omsa.autobus')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='omsa.ruta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='autobus',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='omsa.ruta'),
        ),
        migrations.CreateModel(
            name='UbicacionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('autobus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='omsa.autobus')),
            ],
        ),
    ]
