# Generated by Django 5.2.1 on 2025-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobus',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
