# Generated by Django 5.2.1 on 2025-09-03 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsa', '0002_autobus_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parada',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='parada',
            order_with_respect_to='ruta',
        ),
        migrations.AlterField(
            model_name='parada',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='parada',
            name='lon',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.RemoveField(
            model_name='parada',
            name='orden',
        ),
    ]
