# Generated by Django 5.2.1 on 2025-09-17 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsa', '0003_alter_parada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autobus',
            options={'verbose_name': 'Autobús', 'verbose_name_plural': 'Autobuses'},
        ),
        migrations.AddField(
            model_name='autobus',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_servicio', 'En servicio'), ('mantenimiento', 'En mantenimiento'), ('fuera_de_servicio', 'Fuera de servicio')], default='disponible', max_length=32),
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='11 dígitos, sin guiones.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[\\d\\s+\\-()]+$')])),
                ('correoelectronico', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('descanso', 'Descanso'), ('licencia', 'Licencia'), ('suspendido', 'Suspendido')], default='disponible', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('autobus_actual', models.ForeignKey(blank=True, help_text='Cache del autobús activo hoy. Se actualiza al crear asignaciones de hoy en ventana de turno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choferes_actuales', to='omsa.autobus')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='autobus',
            name='chofer_actual',
            field=models.ForeignKey(blank=True, help_text='Cache del chofer activo hoy. Se actualiza al crear asignaciones de hoy en ventana de turno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autobuses_actuales', to='omsa.chofer'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Mañana, Tarde', max_length=64)),
                ('day_group', models.CharField(choices=[('LV', 'Lunes a Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], help_text='Grupo de días al que aplica.', max_length=2)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
            options={
                'ordering': ['day_group', 'inicio'],
                'unique_together': {('nombre', 'day_group', 'inicio', 'fin')},
            },
        ),
        migrations.CreateModel(
            name='ChoferBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día de trabajo.')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='omsa.autobus')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='omsa.chofer')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='omsa.ruta')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='omsa.turno')),
            ],
            options={
                'ordering': ['-fecha', 'turno__inicio', 'chofer__apellido'],
                'indexes': [models.Index(fields=['fecha', 'turno'], name='omsa_chofer_fecha_941c3b_idx'), models.Index(fields=['autobus', 'fecha', 'turno'], name='omsa_chofer_autobus_e52902_idx'), models.Index(fields=['chofer', 'fecha', 'turno'], name='omsa_chofer_chofer__c7aeef_idx')],
                'constraints': [models.UniqueConstraint(fields=('chofer', 'fecha', 'turno'), name='uniq_chofer_fecha_turno'), models.UniqueConstraint(fields=('autobus', 'fecha', 'turno'), name='uniq_bus_fecha_turno')],
            },
        ),
    ]
