# Generated by Django 5.2.1 on 2025-09-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsa', '0004_alter_autobus_options_autobus_estado_chofer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_servicios', to='omsa.autobus')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_servicios', to='omsa.chofer')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_servicios', to='omsa.ruta')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_servicios', to='omsa.turno')),
            ],
            options={
                'verbose_name': 'Historial de servicios',
                'verbose_name_plural': 'Historial de servicios',
                'ordering': ['-fecha', 'turno__inicio', 'chofer__apellido'],
            },
        ),
        migrations.CreateModel(
            name='ServiciosDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día de trabajo.')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_diarios', to='omsa.autobus')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_diarios', to='omsa.chofer')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_diarios', to='omsa.ruta')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_diarios', to='omsa.turno')),
            ],
            options={
                'verbose_name': 'Servicio diario',
                'verbose_name_plural': 'Servicios diarios',
                'ordering': ['-fecha', 'turno__inicio', 'chofer__apellido'],
            },
        ),
        migrations.DeleteModel(
            name='ChoferBus',
        ),
        migrations.AddIndex(
            model_name='historialservicios',
            index=models.Index(fields=['fecha', 'turno'], name='omsa_histor_fecha_048b38_idx'),
        ),
        migrations.AddIndex(
            model_name='historialservicios',
            index=models.Index(fields=['autobus', 'fecha', 'turno'], name='omsa_histor_autobus_9f232d_idx'),
        ),
        migrations.AddIndex(
            model_name='historialservicios',
            index=models.Index(fields=['chofer', 'fecha', 'turno'], name='omsa_histor_chofer__100b35_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciosdiarios',
            index=models.Index(fields=['fecha', 'turno'], name='omsa_servic_fecha_d10f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciosdiarios',
            index=models.Index(fields=['autobus', 'fecha', 'turno'], name='omsa_servic_autobus_522d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciosdiarios',
            index=models.Index(fields=['chofer', 'fecha', 'turno'], name='omsa_servic_chofer__bafb5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviciosdiarios',
            constraint=models.UniqueConstraint(fields=('chofer', 'fecha', 'turno'), name='uniq_sd_chofer_fecha_turno'),
        ),
        migrations.AddConstraint(
            model_name='serviciosdiarios',
            constraint=models.UniqueConstraint(fields=('autobus', 'fecha', 'turno'), name='uniq_sd_bus_fecha_turno'),
        ),
    ]
