# Generated by Django 5.2.1 on 2025-09-17 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsa', '0005_historialservicios_serviciosdiarios_delete_choferbus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('robo', 'Robo'), ('objeto_perdido', 'Objeto perdido'), ('reclamacion', 'Reclamación'), ('sugerencia', 'Sugerencia')], max_length=32)),
                ('descripcion', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='omsa.ruta')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
