# Generated by Django 5.2.1 on 2025-09-18 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsa', '0006_alter_chofer_options_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='nombre',
            field=models.CharField(choices=[('robo', 'Robo'), ('objeto_perdido', 'Objeto perdido'), ('conduccion_temeraria', 'Conducción Temeraria'), ('sugerencia', 'Sugerencia')], max_length=32),
        ),
        migrations.CreateModel(
            name='CalificacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('follow_id', models.CharField(blank=True, default='', max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='omsa.ruta')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
